"""Manufacturing package: Gerbers, drills, BOM, CPL, KiCad project, README → zip."""
from __future__ import annotations

import csv
import io
import json
import os
import zipfile
from datetime import datetime

from .gerber import write_gerbers
from .kicad_export import write_kicad_pcb, write_kicad_pro, run_kicad_drc, kicad_export_gerbers, kicad_render_png
from .model import Board


def bom_csv(board: Board) -> str:
    """JLCPCB-style BOM: Comment, Designator, Footprint, LCSC Part #."""
    groups: dict[tuple, list[str]] = {}
    for c in board.components:
        if c.footprint.style == "hole":
            continue
        key = (c.value or c.part.name, c.footprint.name, c.part.lcsc, c.part.name)
        groups.setdefault(key, []).append(c.ref)
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["Comment", "Designator", "Footprint", "LCSC Part #", "Manufacturer Part", "Qty", "Unit Price (USD)"])
    for (val, fp, lcsc, name), refs in sorted(groups.items(), key=lambda kv: kv[1][0]):
        price = next(c.part.price for c in board.components if c.ref == refs[0])
        w.writerow([val, ",".join(refs), fp, lcsc, name, len(refs), f"{price:.3f}"])
    return buf.getvalue()


def cpl_csv(board: Board) -> str:
    """JLCPCB pick-and-place: Designator, Mid X, Mid Y, Layer, Rotation."""
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["Designator", "Mid X", "Mid Y", "Layer", "Rotation"])
    for c in board.components:
        if c.footprint.style == "hole":
            continue
        w.writerow([c.ref, f"{c.x:.3f}mm", f"{c.y:.3f}mm", "Top", c.rot])
    return buf.getvalue()


def netlist_json(board: Board) -> str:
    return json.dumps({
        "name": board.name,
        "components": [{"ref": c.ref, "part": c.part.id, "name": c.part.name, "value": c.value, "footprint": c.footprint.name, "lcsc": c.part.lcsc,
                        "x": c.x, "y": c.y, "rot": c.rot, "purpose": c.purpose} for c in board.components],
        "nets": [n.to_json() for n in board.nets],
    }, indent=1)


def readme(board: Board, design: dict, drc: dict, kicad: dict | None, stats: dict) -> str:
    lines = [f"# {board.name} — generated by ETCH", "",
             design.get("tagline", ""), "", design.get("summary", ""), "",
             f"Board: {board.width} x {board.height} mm, 2 layers, 1.6 mm FR-4, 1 oz copper, {board.color} solder mask.",
             f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}.", "",
             "## Contents", "- gerbers/            RS-274X Gerbers + Excellon drills (ETCH writer) — upload the zip to JLCPCB/PCBWay as-is",
             "- kicad/              KiCad 9/10 project (.kicad_pcb + .kicad_pro) — open, inspect, edit",
             "- kicad/gerbers/      Gerbers exported by kicad-cli from the same board (when KiCad is installed)",
             "- bom.csv             JLCPCB assembly BOM with LCSC part numbers", "- cpl.csv             Pick-and-place (component placement) file",
             "- netlist.json        Full netlist + placement", "- design.json         The agent's design brief", "",
             "## Design rules", f"- Min trace 0.2 mm (fab min 0.127), routing clearance 0.18 mm (fab min 0.127), vias 0.6/0.3 mm",
             f"- ETCH DRC: {'PASS' if drc.get('passed') else 'FAIL'} ({drc.get('errors', 0)} errors, {drc.get('warnings', 0)} warnings)"]
    if kicad and kicad.get("available"):
        lines.append(f"- KiCad {kicad.get('kicad_version', '')} DRC: {'PASS' if kicad.get('drc_passed') else 'FAIL'} "
                     f"({kicad.get('violations', 0)} errors, {kicad.get('warnings', 0)} warnings, {kicad.get('unconnected', 0)} unconnected)")
    lines += ["", "## Stats"] + [f"- {k}: {v}" for k, v in stats.items()]
    lines += ["", "## Notes from the agent"] + [f"- {n}" for n in design.get("notes", [])]
    return "\n".join(lines) + "\n"


def export_all(board: Board, design: dict, drc: dict, stats: dict, out_dir: str, keepouts=None, with_kicad_cli: bool = True) -> dict:
    os.makedirs(out_dir, exist_ok=True)
    name = board.name.replace(" ", "_")
    files = []
    gerbers = write_gerbers(board, keepouts)
    gdir = os.path.join(out_dir, "gerbers")
    os.makedirs(gdir, exist_ok=True)
    for fn, content in gerbers.items():
        with open(os.path.join(gdir, fn), "w") as f:
            f.write(content)
        files.append({"name": f"gerbers/{fn}", "kind": "drill" if fn.endswith(".drl") else "gerber", "size": len(content)})
    kdir = os.path.join(out_dir, "kicad")
    os.makedirs(kdir, exist_ok=True)
    pcb = write_kicad_pcb(board, keepouts)
    pcb_path = os.path.join(kdir, f"{name}.kicad_pcb")
    with open(pcb_path, "w") as f:
        f.write(pcb)
    with open(os.path.join(kdir, f"{name}.kicad_pro"), "w") as f:
        f.write(write_kicad_pro(board))
    files.append({"name": f"kicad/{name}.kicad_pcb", "kind": "kicad", "size": len(pcb)})
    files.append({"name": f"kicad/{name}.kicad_pro", "kind": "kicad", "size": 1000})
    kicad = None
    if with_kicad_cli:
        kicad = run_kicad_drc(pcb_path)
        if kicad and kicad.get("available") and "error" not in kicad:
            exported = kicad_export_gerbers(pcb_path, os.path.join(kdir, "gerbers"))
            for fn in exported:
                files.append({"name": f"kicad/gerbers/{fn}", "kind": "gerber", "size": os.path.getsize(os.path.join(kdir, "gerbers", fn))})
            png = os.path.join(out_dir, "render-top.png")
            if kicad_render_png(pcb_path, png, "top"):
                files.append({"name": "render-top.png", "kind": "image", "size": os.path.getsize(png)})
                kicad["render"] = "render-top.png"
    for fn, content in (("bom.csv", bom_csv(board)), ("cpl.csv", cpl_csv(board)), ("netlist.json", netlist_json(board)),
                        ("design.json", json.dumps(design, indent=1)), ("README.md", readme(board, design, drc, kicad, stats))):
        with open(os.path.join(out_dir, fn), "w") as f:
            f.write(content)
        files.append({"name": fn, "kind": fn.split(".")[-1], "size": len(content)})
    zip_name = f"etch-{name.lower()}.zip"
    zip_path = os.path.join(out_dir, zip_name)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for root, _, fns in os.walk(out_dir):
            for fn in fns:
                if fn.endswith(".zip"):
                    continue
                p = os.path.join(root, fn)
                z.write(p, os.path.relpath(p, out_dir))
    # a second zip with only the gerbers, ready for JLCPCB upload
    gz_name = f"etch-{name.lower()}-gerbers-only.zip"
    with zipfile.ZipFile(os.path.join(out_dir, gz_name), "w", zipfile.ZIP_DEFLATED) as z:
        for fn in gerbers:
            z.write(os.path.join(gdir, fn), fn)
    return {"files": files, "zip": zip_name, "gerber_zip": gz_name, "kicad": kicad or {"available": False}}
